server:
  port: 8080
logging:
  level:
    root: DEBUG
spring:
  cloud:
    consul:
      ## 服务发现相关配置
      discovery:
        register: false # 是否需要注册
      # Consul 服务器地址
      host: localhost
      port: 8500