

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://rm-uf6tpisqevjobg5o43o.mysql.rds.aliyuncs.com:3306/todolist
    username: todolist
    password: Aliyun@liu5689
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5